### ISSUE TITLE
Enum v3 support?

### ISSUE THREAD

**Issue by TheM1984** [artkonekt/enum-eloquent#5]
As far as I can see the [Enum v3](https://github.com/artkonekt/enum) is not that much breaking.

However the composer.json does state `"konekt/enum": "^2.0.2",` am I mistaken or can we just change this to `"konekt/enum": "^2.0.2 || ^3.0.0",`?

**Comment by fulopattila122** [comment]
Yes, I think `konekt/enum": "^2.0.2 || ^3.0.0"` is a good way to go.

The reason why it hasn't been done yet is to scan through the code and add tests (if necessary) to cover both v2 and v3.

PRs are more than welcome :smiley:

**Comment by TheM1984** [comment]
Not sure what tests could be added for this, however I will look into creating a fork and a PR in a week or so :-)

**Comment by fulopattila122** [comment]
I think what we have to cover is:
- keep the existing tests, but
- test against both Enum v2 and v3 (it's mainly tuning the travis matrix)
- the test "dummies" contain `__default` const values, let's check if they break or not
- not directly related but I see there's no testing against Laravel 5.8 - I'd add that as well to the travis matrix

I'm also fine with forging the new release together, so if you can't address all the items, I'm still happy to receive a kickstart PR ;)

**Comment by TheM1984** [comment]
Took me a couple of tries with Travis, but it looks like I checked all the boxes.

I have not added Laravel 6 support, since I have not looked into that at the moment.

Hope this is enough for a good kickstart or maybe even a release :-).

**Comment by fulopattila122** [comment]
Included in release [v1.3.0](https://packagist.org/packages/konekt/enum-eloquent#1.3.0).

Thanks for the PR! :clap:
