### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by litvinjuan** [artkonekt/enum-eloquent#6]
Attempting to upgrade to laravel 6.0 fails due to a illuminate/database requirement on the enum-eloquent package.
![image](https://user-images.githubusercontent.com/42967171/64072679-69ca2a80-cc69-11e9-92e6-c00b212f5834.png)

**Comment by fulopattila122** [comment]
I'm aware, although Laravel 6.0 will be released on 3rd September only, so it'll be tackled in the second half of the week.

**Comment by fulopattila122** [comment]
Version 1.3.1 has been released today, which includes Laravel 6.0 is support.
Thanks for the report!
