### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Davidnadejdin** [artkonekt/enum-eloquent#9]
How do you like the idea that when you assign a specific value to a casted property, a specific event is fired?

```
class Status extends Enum
{
    public const NEW = 'new';
    public const PAID = 'paid';
    public const REJECTED = 'rejected';

    protected static $events= [
        self::NEW => ModelNewStatus::class,
        self::PAID => ModelPaidStatus::class,
        self::REJECTED => ModelRejectedStatus::class,
    ];
}
```

**Comment by fulopattila122** [comment]
You can achieve this functionality by adding this to your model in your application:

```php
    public static function boot()
    {
        parent::boot();
        static::saving(function ($model) {
            $model->dispatchEvents();
        });
    }

    public function dispatchEvents()
    {
        $updatedAttributes = $this->getDirty();
        foreach ($updatedAttributes as $attribute => $value) {
            if ($this->isEnumAttribute($attribute)) {
                $class = $this->getEnumClass($attribute);
                $enum = $class::create($value);
                $eventClass = $enum->event();
                if ($eventClass) {
                    event(new $eventClass($this));
                }
            }
        }
    }
```

if you use it frequently, you can outsource it to a trait and use it in multiple models.

**Comment by Davidnadejdin** [comment]
> You can achieve this functionality by adding this to your model in your application:
> 
> ```
>     public static function boot()
>     {
>         parent::boot();
>         static::saving(function ($model) {
>             $model->dispatchEvents();
>         });
>     }
> 
>     public function dispatchEvents()
>     {
>         $updatedAttributes = $this->getDirty();
>         foreach ($updatedAttributes as $attribute => $value) {
>             if ($this->isEnumAttribute($attribute)) {
>                 $class = $this->getEnumClass($attribute);
>                 $enum = $class::create($value);
>                 $eventClass = $enum->event();
>                 if ($eventClass) {
>                     event(new $eventClass($this));
>                 }
>             }
>         }
>     }
> ```
> 
> if you use it frequently, you can outsource it to a trait and use it in multiple models.

You just copied my code from my pool request 🤨

**Comment by Davidnadejdin** [comment]
> You can achieve this functionality by adding this to your model in your application:

No I can not. The `event()` method does not have an enum class. I also added it in my pull-quest.

**Comment by fulopattila122** [comment]
The event method can dispatch any event class you define. It's the responsibility of the Eloquent model not this package.

**Comment by Davidnadejdin** [comment]
> The event method can dispatch any event class you define. It's the responsibility of the Eloquent model not this package.

I suggest that enum do it

**Comment by fulopattila122** [comment]
I would solve this problem by hooking into the model's lifecycle events:

https://laravel.com/docs/5.8/eloquent#events

Mixing typecasting (what this library does) and event handling (handled by eloquent) is mixing of concerns.

https://en.wikipedia.org/wiki/Single_responsibility_principle
https://en.wikipedia.org/wiki/Separation_of_concerns

**Comment by Davidnadejdin** [comment]
> Mixing typecasting (what this library does) and event handling (handled by eloquent) is mixing of concerns.

do not you think that in the context of laravel events these principles do not work?

**Comment by Davidnadejdin** [comment]
> I would solve this problem by hooking into the model's lifecycle events:
> 
> https://laravel.com/docs/5.8/eloquent#events
> 
> Mixing typecasting (what this library does) and event handling (handled by eloquent) is mixing of concerns.
> 
> https://en.wikipedia.org/wiki/Single_responsibility_principle
> https://en.wikipedia.org/wiki/Separation_of_concerns

event handling is not tied to eloquent in any way
